'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Profesion
    Public Property idProfesion As Integer
    Public Property nombreProfesion As String

    Public Overridable Property Personas As ICollection(Of Personas) = New HashSet(Of Personas)

End Class
